In [1]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import scipy as sp
import sympy as sy
sy.init_printing() 

In [2]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # display multiple results

In [4]:
def round_expr(expr, num_digits):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sy.Number)})

# <font face="黑体" color="purple"> 矩阵的概念和运算</font>

## <font face="黑体" color="DarkViolet"> 矩阵的概念</font>

 $m\times n$ 个数如下排列成 $m$ 行 $n$ 列的一个表格，称为一个 $m\times n$ **矩阵**，
 当 $m = n$ 时，为**n 阶矩阵**或者**n 阶方阵**。
 
$$
\left[\begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1 n} \\
a_{21} & a_{22} & \cdots & a_{2 n} \\
\vdots & \vdots & &\vdots & \\
a_{n 1}& a_{n 2}& \cdots & a_{n n}
\end{array}\right]
$$

1. 一个矩阵中所有元素都为 **0**，称这个矩阵为**零矩阵**。

2. 两个矩阵 $A = {[a_{ij}]}_{m\times n}$ ，$B = {[b_{ij}]}_{s\times t}$ ，如果 $m =s, n = t$ ，则称 $A$ 与 $B$ 是**同型矩阵**。

3. 两个同型矩阵 $A = {[a_{ij}]}_{m\times n}$ ，$B = {[b_{ij}]}_{m\times n}$ ，如果对应元素都相等，即 $a_{ij} = b_{ij} (i = 1, 2, \cdots , m; j = 1, 2, \cdots , n )$ ，$$\qquad $$则称矩阵 $A$ 与 $B$ **相等**，记作**A = B**。

## <font face="黑体" color="DarkViolet"> 矩阵的运算</font>

矩阵加法运算法则如下:
1. $A+ B= B+ A$
2. $(A+B)+ C=A+(B+C)$
3. $c(A+B)=cA+cB$
4. $(c+d)A=cA+c{D}$
5. $c(dA)=(cd)A$
6. $A+{0}=A$,  ${0}$ 是零矩阵
7. 对于任意矩阵 $A$, 总存在矩阵 $- A$, 使得 $ A+(- A)=0$ 成立

矩阵乘法法则如下:
1. $ A({BC})=({AB}) C$
2. $c({AB})=(cA)B=A(cB)$
3. $A(B+ C)={AB}+{AC}$
4. $(B+C)A={BA}+{CA}$
5. $AB \neq BA$ ,矩阵乘法不满足交换性

<font face="黑体" color="DarkOrange" size=3> 矩阵有两种乘法：矩阵点乘和矩阵乘法</font>
    
**点乘**要求两个矩阵为**同型矩阵**，对应元素相乘生成新矩阵
    
**矩阵乘法**要求满足形式为**前项矩阵的列数等于后项矩阵的行数**，具体运算见示例


In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [6]:
A*B # 在numpy定义的向量中" * "表示 点乘 ，而在sympy定义的matrix中" * "表示 矩阵乘法

array([[ 5, 12],
       [21, 32]])

In [7]:
A@B # numpy中表示 矩阵乘法

array([[19, 22],
       [43, 50]])

In [8]:
# 矩阵乘法具体运算步骤
np.sum(A[0,:]*B[:,0]) # 新矩阵的(1, 1)
np.sum(A[1,:]*B[:,0]) # (2, 1)
np.sum(A[0,:]*B[:,1]) # (1, 2)
np.sum(A[1,:]*B[:,1]) # (2, 2)

19

43

22

50

$\ast$ **矩阵加法Sympy示例**

In [9]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real = True)

In [10]:
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A
A - A

⎡2⋅a  2⋅b  2⋅c⎤
⎢             ⎥
⎣2⋅d  2⋅e  2⋅f⎦

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [11]:
B = sy.Matrix([[g, h, i], [j, k, l]])
A + B
A - B

⎡a + g  b + h  c + i⎤
⎢                   ⎥
⎣d + j  e + k  f + l⎦

⎡a - g  b - h  c - i⎤
⎢                   ⎥
⎣d - j  e - k  f - l⎦

$\ast$ **矩阵乘法Sympy示例**

In [12]:
A = sy.Matrix([[a, b, c], [d, e, f]])
B = sy.Matrix([[g, h, i], [j, k, l], [m, n, o]])
A
B

⎡a  b  c⎤
⎢       ⎥
⎣d  e  f⎦

⎡g  h  i⎤
⎢       ⎥
⎢j  k  l⎥
⎢       ⎥
⎣m  n  o⎦

In [13]:
AB = A*B; AB

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

$\ast$ **矩阵乘法的不可交换性的Sympy证明**

In [14]:
A = sy.Matrix([[a, b], [c, d]])
B = sy.Matrix([[e, f], [g, h]])
A*B
B*A

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

⎡a⋅e + c⋅f  b⋅e + d⋅f⎤
⎢                    ⎥
⎣a⋅g + c⋅h  b⋅g + d⋅h⎦

若 $AB = BA$ , 那么 $AB - BA = 0$

In [15]:
M = A*B - B*A; M

⎡      b⋅g - c⋅f         a⋅f - b⋅e + b⋅h - d⋅f⎤
⎢                                             ⎥
⎣-a⋅g + c⋅e - c⋅h + d⋅g       -b⋅g + c⋅f      ⎦

通常情况下，$M$ 不为零矩阵

若 $M$ 是零矩阵，则，
\begin{align}
b g - c f&=0 \\
 a f - b e + b h - d f&=0\\
- a g + c e - c h + d g&=0 \\
- b g + c f&=0
\end{align}

$a b c d$ 视为系数，解方程组

In [16]:
A_aug = sy.Matrix([[0, -c, b, 0], [-b, a-d, 0, b], [c, 0, d -a, -c], [0, c, -b, 0]]); A_aug

⎡0    -c      b     0 ⎤
⎢                     ⎥
⎢-b  a - d    0     b ⎥
⎢                     ⎥
⎢c     0    -a + d  -c⎥
⎢                     ⎥
⎣0     c      -b    0 ⎦

In [17]:
A_aug.rref() # 用 Gaussian-Jordon 消元化为行阶梯矩阵

⎛⎡        a   d    ⎤        ⎞
⎜⎢1  0  - ─ + ─  -1⎥        ⎟
⎜⎢        c   c    ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢        -b       ⎥        ⎟
⎜⎢0  1    ───    0 ⎥, (0, 1)⎟
⎜⎢         c       ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢0  0     0     0 ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎝⎣0  0     0     0 ⎦        ⎠

方程组化为
\begin{align}
e - \frac{a-d}cg - h &=0\\
f - \frac{b}{c} & =0\\
g &= free\\
h & =free
\end{align}

假设 $a = 10, b = 12, c = 20, d = 8$, or $ A = \left[\begin{matrix}10 & 12\\20 & 8\end{matrix}\right]$ 则方程组化为


\begin{align}
e - .1g - h &=0\\
f - .6 & =0\\
g &= free\\
h & =free
\end{align}
设 $g = h = 1$
\begin{align}
e  &=1.1\\
f & =.6\\
g &=1 \\
h & =1
\end{align}
即可得到与$A$ 相乘满足可交换性的矩阵 $ C$.

In [18]:
C = sy.Matrix([[1.1, .6], [1, 1]]);C

⎡1.1  0.6⎤
⎢        ⎥
⎣ 1    1 ⎦

In [19]:
A = sy.Matrix([[10, 12], [20, 8]])
A*C
C*A

⎡23.0  18.0⎤
⎢          ⎥
⎣30.0  20.0⎦

⎡23.0  18.0⎤
⎢          ⎥
⎣ 30    20 ⎦

将 $m\times n$ 型矩阵 $A = {[a_{ij}]}_{m\times N}$ 的行列互换得到的 $n\times m$ 矩阵 ${[a_{ji}]}_{n\times m}$ 称为 $A$ 的**转置矩阵**，记为 $A^T$
$$
A = \left[\begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1 n} \\
a_{21} & a_{22} & \cdots & a_{2 n} \\
\vdots & \vdots & &\vdots & \\
a_{n 1}& a_{n 2}& \cdots & a_{n n}
\end{array}\right]
\qquad A^T = \left[\begin{array}{cccc}
a_{11} & a_{21} & \cdots & a_{n 1} \\
a_{12} & a_{22} & \cdots & a_{n 2} \\
\vdots & \vdots & &\vdots & \\
a_{1 n}& a_{2 n}& \cdots & a_{n n}
\end{array}\right]
$$

转置的运算法则
1. $(A^T)^T=A$
2. $(A+B)^T=A^T+B^T$
3. $(cA)^T=cA^T$
4. $(AB)^T=B^TA^T$


In [20]:
# Sympy证明转置性质4
A = sy.Matrix([[a, b], [c, d], [e, f]])
B = sy.Matrix([[g, h, i], [j, k, l]])
AB = A*B
AB_tr = AB.transpose(); AB_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

In [21]:
B_tr_A_tr = B.transpose()*A.transpose()
B_tr_A_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

In [22]:
AB_tr - B_tr_A_tr

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

# <font face="黑体" color="purple"> 伴随矩阵和可逆矩阵</font>

## <font face="黑体" color="DarkViolet"> 伴随矩阵</font>

在行列式按行（列）展开中，我们学习了**代数余子式**，

$A$ 的 $(i,j)$ 元素的代数余子式记作 $C_{ij}$ 
$$C_{i j}=(-1)^{i+j} \operatorname{det} A_{i j} = (-1)^{i+j} M_{ij}$$

$M_{ij}$ 是除去第 $i$ 行和第 $j$ 列的其他元素组成的行列式，称为**余子式**

**伴随矩阵**：由矩阵 $A$ 的行列式 $|A|$ 所有的代数余子式构成的形如

$$
\left[\begin{array}{cccc}
C_{11} & C_{12} & \cdots & C_{1 n} \\
C_{21} & C_{22} & \cdots & C_{2 n} \\
\vdots & \vdots & &\vdots & \\
C_{n 1}& C_{n 2}& \cdots & C_{n n}
\end{array}\right]
$$
的矩阵称为矩阵 $A$ 的**伴随矩阵**，记为 $A^{*}$ （$|A|$每个元素对应代数余子式按元素位置构成的矩阵再取转置）

**伴随矩阵的公式**：
1. $AA^{*} = A^{*}A = |A|E \qquad E\text{是单位矩阵}$
2. ${(A^*)}^{-1} = {(A^{-1})}^{*} = \frac {1}{|A|} A \qquad |A| \neq 0$
3. ${(kA)}^{*} = k^{n-1}A^*$
4. ${A^*}^{T} = {A^T}^{*}$
5. $|A^*| = {|A|}^{n-1}$
6. ${(A^*)}^* = {|A|}^{n-2} (n\geq 2)$

## <font face="黑体" color="DarkViolet"> 可逆矩阵</font>

设 $A$是 $n$ 阶矩阵，如果存在 $n$ 阶矩阵 $B$ 使得
$$ AB = BA = E $$
成立，则称 $A$ 是**可逆矩阵**， $B$ 是 $A$ 的逆矩阵，记成$A^{-1} = B$

**定理**：
1. 若 $A$ 可逆，则$A$的逆矩阵唯一；
2. $A$ 可逆 $\Leftrightarrow |A|\neq 0$
3. $A$ 和 $B$ 是$n$ 阶矩阵且$ AB = E$ ，则$ BA =E $


**可逆矩阵运算性质**：

1. 如果 $A$ 和 $B$ 都可逆, 那么 $(AB)^{-1}=B^{-1}A^{-1}$.
2. 如果 $A$ 肯, 那么 $(A^T)^{-1}=(A^{-1})^T$.
3. 如果 $A$ 和 $B$ 可逆且对称，当 $AB=BA$,  $A^{-1}B$ 是对称的 .

**性质1 证明**
\begin{align}
ABB^{-1}A^{-1}=AIA^{-1}=I=AB(AB)^{-1}
\end{align}

**性质3 证明**

求证
$$
A^{-1}B = (A^{-1}B)^T
$$
使用转置的性质
$$
(A^{-1}B)^{T}=B^T(A^{-1})^T=B(A^T)^{-1}=BA^{-1}
$$
使用条件 $AB = BA$ 
\begin{align}
AB&=BA\\
A^{-1}ABA^{-1}&=A^{-1}BAA^{-1}\\
BA^{-1}&=A^{-1}B
\end{align}
结合两个等式得
$$
(A^{-1}B)^{T}=BA^{-1}=A^{-1}B
$$

$\ast$ **Numpy求逆示例**

In [23]:
A = np.round(10*np.random.randn(5,5)); A

array([[ 12.,  22.,   2.,   0.,  -6.],
       [ -6.,   2.,  -1.,   5.,  -4.],
       [ -5.,  19.,  -5.,  12., -12.],
       [  3., -13.,   8.,  -3., -12.],
       [ -5.,   7.,   1.,  14.,  -0.]])

In [24]:
Ainv = np.linalg.inv(A); Ainv

array([[-0.069, -0.438,  0.138,  0.043,  0.047],
       [ 0.074,  0.208, -0.072, -0.035, -0.02 ],
       [ 0.142,  0.444, -0.222,  0.002,  0.032],
       [-0.072, -0.292,  0.101,  0.032,  0.096],
       [ 0.015,  0.034, -0.061, -0.041,  0.031]])

In [25]:
A@Ainv

array([[ 1., -0., -0., -0., -0.],
       [-0.,  1.,  0.,  0.,  0.],
       [-0.,  0.,  1.,  0., -0.],
       [ 0., -0., -0.,  1.,  0.],
       [ 0.,  0., -0., -0.,  1.]])

 ```-0.```意味小数点后仍有多位数字,但此处省略.

<font face="黑体" color="DarkOrange" size=3> 使用伴随矩阵求逆矩阵</font>

$$A^{-1}=\frac{1}{\operatorname{det} A}\left[\begin{array}{cccc}
C_{11} & C_{21} & \cdots & C_{n 1} \\
C_{12} & C_{22} & \cdots & C_{n 2} \\
\vdots & \vdots & & \vdots \\
C_{1 n} & C_{2 n} & \cdots & C_{n n}
\end{array}\right]$$

等式右边的矩阵是 $A$的 **伴随矩阵** , SymPy 对应函数 ```sy.matrices.matrices.MatrixDeterminant.adjugate```. 

并且是**代数余子式矩阵**的**转置**，其Sympy函数是 ```sy.matrices.matrices.MatrixDeterminant.cofactor_matrix```

$\ast$ **伴随矩阵求逆Sympy示例**

In [26]:
A = sy.randMatrix(5, min=-5, max = 5, percent = 80); A

⎡2   5  0   4   0 ⎤
⎢                 ⎥
⎢-3  0  1   5   3 ⎥
⎢                 ⎥
⎢0   1  -4  -3  0 ⎥
⎢                 ⎥
⎢0   0  4   -5  -3⎥
⎢                 ⎥
⎣0   0  4   5   -3⎦

In [27]:
A_adjugate = sy.matrices.matrices.MatrixDeterminant.adjugate(A); A_adjugate # A 的伴随矩阵

⎡-150  600   750   315   285 ⎤
⎢                            ⎥
⎢-360  -240  -300  -294   54 ⎥
⎢                            ⎥
⎢-90   -60   450   -231  171 ⎥
⎢                            ⎥
⎢ 0     0     0    210   -210⎥
⎢                            ⎥
⎣-120  -80   600    42   578 ⎦

我们可以取$A$ 的几个代数余子式进行检验，如取 $A$ 的$(1, 3), (2, 4), (5, 4)$ 元素求其代数余子式 

```注意 这几个元素的代数余子式在伴随矩阵中的位置是 (3, 1), (4, 2), (4, 5) ```

In [28]:
(-1)**(1+3) * sy.matrices.matrices.MatrixDeterminant.minor(A, 0, 2) 
(-1)**(2+4) * sy.matrices.matrices.MatrixDeterminant.minor(A, 1, 3)
(-1)**(5+4) * sy.matrices.matrices.MatrixDeterminant.minor(A, 4, 3)

 ```sy.N()``` 将数值转换为近似浮点数.

In [29]:
A_det = A.det()
A_inv = (1/A_det)*A_adjugate  # 使用伴随矩阵求逆矩阵
round_expr(sy.N(A_inv), 4)

⎡0.0714  -0.2857  -0.3571  -0.15  -0.1357⎤
⎢                                        ⎥
⎢0.1714  0.1143   0.1429   0.14   -0.0257⎥
⎢                                        ⎥
⎢0.0429  0.0286   -0.2143  0.11   -0.0814⎥
⎢                                        ⎥
⎢  0        0        0     -0.1     0.1  ⎥
⎢                                        ⎥
⎣0.0571  0.0381   -0.2857  -0.02  -0.2752⎦

In [30]:
round_expr(sy.N(A.inv()), 4)  # 内置函数求逆矩阵

⎡0.0714  -0.2857  -0.3571  -0.15  -0.1357⎤
⎢                                        ⎥
⎢0.1714  0.1143   0.1429   0.14   -0.0257⎥
⎢                                        ⎥
⎢0.0429  0.0286   -0.2143  0.11   -0.0814⎥
⎢                                        ⎥
⎢  0        0        0     -0.1     0.1  ⎥
⎢                                        ⎥
⎣0.0571  0.0381   -0.2857  -0.02  -0.2752⎦

In [31]:
A_inv-A.inv()

⎡0  0  0  0  0⎤
⎢             ⎥
⎢0  0  0  0  0⎥
⎢             ⎥
⎢0  0  0  0  0⎥
⎢             ⎥
⎢0  0  0  0  0⎥
⎢             ⎥
⎣0  0  0  0  0⎦

# <font face="黑体" color="Purple"> 初等变换和初等矩阵</font>

## <font face="黑体" color="DarkViolet"> 初等变换</font>

1. **倍乘**：用非零常数$k$ 乘以矩阵$A$ 某行（列）的每个元素
2. **互换**：互换矩阵$A$ 中两行（列）元素的位置
3. **倍加**：把某行（列）所有元素的$k$ 另一行（列）对应元素上

## <font face="黑体" color="DarkViolet"> 单位矩阵</font>

In [32]:
sy.eye(5) # Sympy生成n阶单位矩阵

⎡1  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  0  1  0  0⎥
⎢             ⎥
⎢0  0  0  1  0⎥
⎢             ⎥
⎣0  0  0  0  1⎦

单位矩阵性质：
$$
AI=IA = A
$$

In [33]:
I = np.eye(5); I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
A = np.around(np.random.rand(5, 5)*100); A # 生成一个随机矩阵

array([[60., 53., 36., 58., 75.],
       [31., 62., 57., 15.,  1.],
       [18., 77., 92., 71., 21.],
       [95., 55., 33., 86., 90.],
       [77., 77.,  6., 44., 97.]])

In [35]:
A@I - I@A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## <font face="黑体" color="DarkViolet"> 初等矩阵</font>

1. 单位矩阵经过一次初等变换得到的矩阵就是**初等矩阵**
2. 初等矩阵$P$ 左乘（右乘）矩阵$A$ ，得到的$PA (AP)$ ，结果相当于对矩阵$A$ 做一次和$P$ 相同的初等行（列）变换

In [36]:
A = sy.randMatrix(3, percent = 80); A # 生成一个80%元素非零的3阶矩阵

⎡99  9   0 ⎤
⎢          ⎥
⎢18  50  54⎥
⎢          ⎥
⎣69  36  0 ⎦

In [37]:
P1 = sy.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]]);P1

⎡0  1  0⎤
⎢       ⎥
⎢1  0  0⎥
⎢       ⎥
⎣0  0  1⎦

In [38]:
P1*A
A*P1

⎡18  50  54⎤
⎢          ⎥
⎢99  9   0 ⎥
⎢          ⎥
⎣69  36  0 ⎦

⎡9   99  0 ⎤
⎢          ⎥
⎢50  18  54⎥
⎢          ⎥
⎣36  69  0 ⎦

In [39]:
P2 = sy.Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 10]]);P2

⎡1  0  0 ⎤
⎢        ⎥
⎢0  1  0 ⎥
⎢        ⎥
⎣0  0  10⎦

In [40]:
P2*A
A*P2

⎡99    9   0 ⎤
⎢            ⎥
⎢18   50   54⎥
⎢            ⎥
⎣690  360  0 ⎦

⎡99  9    0 ⎤
⎢           ⎥
⎢18  50  540⎥
⎢           ⎥
⎣69  36   0 ⎦

## <font face="黑体" color="DarkViolet"> 初等变换求逆矩阵</font>

初等变换在求解逆矩阵时可以把矩阵$A$ 和同阶的$I$ 合并成$[A|I]$ ，对该矩阵做初等行变换，如果矩阵$A$存在逆矩阵的话，可以得到$[I|A]$

证明：
由可逆的定义可知
$$
AA^{-1} = A^{-1}A = I
$$

一系列初等行变换相当于在矩阵$A$左乘初等矩阵$P_1, P_2, \cdots , P_n$

$$
(P_n\cdots P_2P_1)A = I, \qquad (P_n\cdots P_2P_1) = A^{-1}
$$

对$I$做相同的初等行变换相当于左乘相同的初等矩阵$P_1, P_2, \cdots , P_n$

$$
(P_n\cdots P_2P_1)I = P_n\cdots P_2P_1 =A^{-1}
$$

In [41]:
A = np.round(10*np.random.randn(5,5)); A

array([[  9.,  -8.,  -4., -11., -16.],
       [ 16.,   3.,  -1.,  11.,   3.],
       [  1.,   7.,  -7.,  12.,   0.],
       [ -0.,  10.,  -6., -14.,   3.],
       [  4.,   2.,   6.,  -8.,  10.]])

In [42]:
I = np.eye(5); I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
AI = np.hstack((A, I)) # stack the matrix A and I horizontally
AI = sy.Matrix(AI); AI

⎡9.0   -8.0  -4.0  -11.0  -16.0  1.0   0    0    0    0 ⎤
⎢                                                       ⎥
⎢16.0  3.0   -1.0  11.0    3.0    0   1.0   0    0    0 ⎥
⎢                                                       ⎥
⎢1.0   7.0   -7.0  12.0     0     0    0   1.0   0    0 ⎥
⎢                                                       ⎥
⎢ 0    10.0  -6.0  -14.0   3.0    0    0    0   1.0   0 ⎥
⎢                                                       ⎥
⎣4.0   2.0   6.0   -8.0   10.0    0    0    0    0   1.0⎦

In [44]:
AI_rref = AI.rref(); AI_rref

⎛⎡1  0  0  0  0  0.0364842454394693  0.0265339966832504  0.0315091210613599  -
⎜⎢                                                                            
⎜⎢0  1  0  0  0  -3.28606965174129    4.23134328358209    -8.0273631840796    
⎜⎢                                                                            
⎜⎢0  0  1  0  0  -3.64759535655058    4.69568822553897    -8.9759535655058    
⎜⎢                                                                            
⎜⎢0  0  0  1  0  -0.213930348258706   0.26865671641791   -0.472636815920398   
⎜⎢                                                                            
⎝⎣0  0  0  0  1   2.66003316749585   -3.45936981757877    6.60033167495854    

0.0116086235489221  0.0538971807628524⎤                 ⎞
                                      ⎥                 ⎟
3.32587064676617    -7.52487562189055 ⎥                 ⎟
                                      ⎥                 ⎟
3.62271973466003    -8.33167495854063 ⎥, (0, 1, 2, 3, 4)

In [45]:
Ainv = AI_rref[0][:,5:];Ainv # 逆矩阵为第一层第五列后的部分

⎡0.0364842454394693  0.0265339966832504  0.0315091210613599  -0.01160862354892
⎢                                                                             
⎢-3.28606965174129    4.23134328358209    -8.0273631840796    3.32587064676617
⎢                                                                             
⎢-3.64759535655058    4.69568822553897    -8.9759535655058    3.62271973466003
⎢                                                                             
⎢-0.213930348258706   0.26865671641791   -0.472636815920398   0.17412935323383
⎢                                                                             
⎣ 2.66003316749585   -3.45936981757877    6.60033167495854    -2.6948590381426

21  0.0538971807628524⎤
                      ⎥
    -7.52487562189055 ⎥
                      ⎥
    -8.33167495854063 ⎥
                      ⎥
1   -0.475124378109453⎥
                      ⎥
2    6.20232172470978 ⎦

In [46]:
round_expr(Ainv, 4) 

⎡0.0365   0.0265   0.0315   -0.0116  0.0539 ⎤
⎢                                           ⎥
⎢-3.2861  4.2313   -8.0274  3.3259   -7.5249⎥
⎢                                           ⎥
⎢-3.6476  4.6957   -8.976   3.6227   -8.3317⎥
⎢                                           ⎥
⎢-0.2139  0.2687   -0.4726  0.1741   -0.4751⎥
⎢                                           ⎥
⎣ 2.66    -3.4594  6.6003   -2.6949  6.2023 ⎦

In [47]:
A = sy.Matrix(A)
round_expr(A*Ainv, 4) 

⎡1.0   0    0    0    0 ⎤
⎢                       ⎥
⎢ 0   1.0   0    0    0 ⎥
⎢                       ⎥
⎢ 0    0   1.0   0    0 ⎥
⎢                       ⎥
⎢ 0    0    0   1.0   0 ⎥
⎢                       ⎥
⎣ 0    0    0    0   1.0⎦

# <font face="黑体" color="Purple"> 分块矩阵</font>

在上一小节利用 $[A|I]$ 求逆矩阵的过程中就用到了分块的思想，将矩阵用若干纵线和横线分成许多小块，每一小块称为原矩阵的子块，把子块看作原矩阵的一个元素，则原矩阵叫做**分块矩阵**。

按行分块：
$$
A=\left[\begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1 n} \\
\hline 
a_{21} & a_{22} & \cdots & a_{2 n} \\
\hline 
\vdots & \vdots & &\vdots & \\
\hline
a_{n 1}& a_{n 2}& \cdots & a_{n n}
\end{array}\right]
\qquad = \left[\begin{array}{cccc}
{\alpha }_{1} \\
{\alpha }_{2} \\
\vdots \\
{\alpha }_{n}
\end{array}\right]
$$

按列分块：
$$
B=\left[\begin{array}{c|c|c|c}
b_{11} & b_{12} & \cdots & b_{1 n} \\
b_{21} & b_{22} & \cdots & b_{2 n} \\
\vdots & \vdots & &\vdots & \\
b_{n 1}& b_{n 2}& \cdots & b_{n n}
\end{array}\right]
\qquad = \left[\begin{array}{cccc}
{\beta }_{1} & {\beta }_{2} & \cdots & {\beta }_{n}
\end{array}\right]
$$

按特性分块：
$$
C=\left[\begin{array}{cc|ccc}
c_{11} & c_{12} & {0} & {0} & 0 \\
c_{21} & c_{22} & 0 & 0 & 0 \\
\hline 
c_{31} & c_{32} & c_{33} & c_{34} & c_{35} \\
c_{41}& c_{42} & c_{43} & c_{44} & c_{54}
\end{array}\right]
\qquad = \left[\begin{array}{cccc}
C_{1} & 0 \\
C_{3} & C_{4}
\end{array}\right]
$$

In [53]:
A = np.eye(3)*2; A

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [59]:
B = np.random.rand(4,4); B

array([[0.139, 0.175, 0.452, 0.753],
       [0.097, 0.705, 0.058, 0.634],
       [0.274, 0.465, 0.771, 0.89 ],
       [0.58 , 0.54 , 0.126, 0.513]])

In [61]:
A_B = np.block([[A, np.zeros((3,4))], [np.ones((4,3)), B]]); A_B

array([[2.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 2.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 2.   , 0.   , 0.   , 0.   , 0.   ],
       [1.   , 1.   , 1.   , 0.139, 0.175, 0.452, 0.753],
       [1.   , 1.   , 1.   , 0.097, 0.705, 0.058, 0.634],
       [1.   , 1.   , 1.   , 0.274, 0.465, 0.771, 0.89 ],
       [1.   , 1.   , 1.   , 0.58 , 0.54 , 0.126, 0.513]])